src/TM.UI.MVC/Controllers/CourseController.cs
using System;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using TM.UI.MVC.Models;

namespace TM.UI.MVC.Controllers
{
   using VM = CourseViewModels;

   public class CourseController : ControllerBase<CourseViewModels.CoursesManager>
   {
      public CourseController(CourseViewModels.CoursesManager catalogManager) 
         : base(catalogManager)
      {
      }


      public async Task<ActionResult> CategoryCourses(string trainingProviderName, string categoryUrlName)
      {
         if (string.IsNullOrWhiteSpace(categoryUrlName) || string.IsNullOrWhiteSpace(trainingProviderName))
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }

         var viewModel = await CatalogManager.GetCoursesForCategoryAsync(trainingProviderName, categoryUrlName, UserId, UserSpecializations);

         if (viewModel == null)
         {
            return HttpNotFound();
         }


         return PartialView("_CourseListPartial", viewModel);
      }

      public async Task<ActionResult> AuthorCourses(string trainingProviderName, string authorUrlName )
      {
         if (string.IsNullOrWhiteSpace(authorUrlName) || string.IsNullOrWhiteSpace(trainingProviderName))
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }

         var viewModel = await CatalogManager.GetCoursesForAuthorAsync(authorUrlName, trainingProviderName, UserId, UserSpecializations);

         if (viewModel == null)
         {
            return HttpNotFound();
         }


         return PartialView("_CourseListPartial", viewModel);
      }

      public async Task<ActionResult> AddedCourses(string trainingProviderName, DateTime? addDate)
      {
         if (addDate == null || string.IsNullOrWhiteSpace(trainingProviderName))
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }

         var viewModel = await CatalogManager.GetAddedCoursesForDateAsync(addDate.Value, trainingProviderName, UserId, UserSpecializations);

         if (viewModel == null)
         {
            return HttpNotFound();
         }


         return PartialView("_CourseListPartial", viewModel);;
      }

      public async Task<ActionResult> Top5NewCourses()
      {
         var courses = await CatalogManager.GetTop5NewCoursesAsync(UserSpecializations);

         return PartialView("_TopCourseListPartial", courses);
      }

      public async Task<ActionResult> Top5MonthPopularCourses()
      {
         var courses = await CatalogManager.GetTop5MonthPopularCoursesAsync(UserSpecializations);

         return PartialView("_TopCourseListPartial", courses);
      }


      public ActionResult Courses(string trainingProviderName)
      {
         var courseCatalogViewModel = CatalogManager.GetCourseCatalog(trainingProviderName);

         if (courseCatalogViewModel == null)
         {
            return HttpNotFound();
         }

         return View(courseCatalogViewModel);
      }

      public async Task<ActionResult> Course(string trainingProviderName, string courseUrlName)
      {
         if (string.IsNullOrWhiteSpace(trainingProviderName) || string.IsNullOrWhiteSpace(courseUrlName))
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }

         var courseInfo = await CatalogManager.GetCourseInfoAsync(trainingProviderName,courseUrlName, UserId);

         if (courseInfo == null)
         {
            return HttpNotFound();
         }

         return View(courseInfo);
      }


      public ActionResult Search(string searchTerm)
      {
         var searchViewModel = new CourseViewModels.CourseSearchViewModel
         {
            SearchTerm = searchTerm
         };

         return View(searchViewModel);
      }


      [HttpPost, ValidateAntiForgeryToken]
      public async Task<JsonNetResult> AjaxSearch(CourseViewModels.CourseCatalogSearchRequest searchRequest)
      {
         if (!ModelState.IsValid)
         {
            return JsonNetModelError(searchRequest);
         }

         var searchResult = await CatalogManager.GetCourseCatalogSearchResultAsync(searchRequest, UserId, UserSpecializations);

         return JsonNet(searchResult);
      }
   }
}

src/TM.UI.MVC/Controllers/LearningPlanController.cs
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using TM.UI.MVC.Models;

namespace TM.UI.MVC.Controllers
{
   using VM = LearningPlanViewModels;

   [Authorize]
   public class LearningPlanController : ControllerBase<VM.LearningPlanManager>
   {
      public LearningPlanController(VM.LearningPlanManager catalogManager)
         : base(catalogManager)
      {
      }


      public async Task<ActionResult> LearningPlan()
      {
         var learningPlan = await CatalogManager.GetLearningPlanAsync(UserId, UserSpecializations);

         if (learningPlan == null)
         {
            return View("Empty");
         }

         return View(learningPlan);
      }

      [HttpPost, ValidateAntiForgeryToken]
      public async Task<ActionResult> Add(int courseId)
      {
         if (courseId == 0)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }

         await CatalogManager.AddCourseToLearningPlanAsync(UserId, courseId);

         var courseRouteParam = await CatalogManager.GetCourseRouteParamAsync(courseId);

         return RedirectToRoute(AppConstants.RouteNames.Course, courseRouteParam);
      }


      [HttpPost, ValidateAntiForgeryToken]
      public async Task<ActionResult> AjaxAdd(int courseId)
      {
         if (courseId == 0)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }

         var result = await CatalogManager.AddCourseToLearningPlanAsync(UserId, courseId);

         return result.Succeeded
            ? new HttpStatusCodeResult(HttpStatusCode.NoContent)
            : new HttpStatusCodeResult(HttpStatusCode.BadRequest, result.Errors.First());
      }

      [HttpPost, ValidateAntiForgeryToken]
      public async Task<JsonNetResult> AjaxStart(int courseId)
      {
         var subscriptionChangeResult = await CatalogManager.SetStartStateAsync(courseId, UserId);

         return subscriptionChangeResult.Succeeded
            ? JsonNet(subscriptionChangeResult.Value)
            : JsonNetError(subscriptionChangeResult.Errors);
      }

      [HttpPost, ValidateAntiForgeryToken]
      public async Task<JsonNetResult> AjaxFinish(int courseId)
      {
         var subscriptionChangeResult = await CatalogManager.SetFinishStateAsync(courseId, UserId);

         return subscriptionChangeResult.Succeeded
            ? JsonNet(subscriptionChangeResult.Value)
            : JsonNetError(subscriptionChangeResult.Errors);
      }

      [HttpPost, ValidateAntiForgeryToken]
      public async Task<ActionResult> AjaxDelete(int courseId)
      {
         var result = await CatalogManager.DeleteCourseFromLearningPlanAsync(UserId, courseId);

         return result.Succeeded
            ? (ActionResult)new HttpStatusCodeResult(HttpStatusCode.NoContent)
            : JsonNetError(result.Errors);
      }

      public async Task<ActionResult> Subscription(int? courseId)
      {
         if (courseId == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }

         var subscriptionInfoResult = await CatalogManager.GetCourseSubscriptionInfoAsync(UserId, courseId.Value);

         if (subscriptionInfoResult.Succeeded)
         {
            return PartialView("_SubscriptionFormPartial", subscriptionInfoResult.Value);
         }

         return new HttpStatusCodeResult(HttpStatusCode.BadRequest, subscriptionInfoResult.Errors.First());
      }

      [HttpPost, ValidateAntiForgeryToken]
      public async Task<JsonNetResult> Subscription(LearningPlanViewModels.SubscriptionViewModel subscription)
      {
         if (ModelState.IsValid)
         {
            var result = await CatalogManager.UpdateCourseSubscriptionInfoAsync(UserId, subscription);

            if (result.Succeeded)
            {
               return JsonNet(subscription);
            }

            subscription.IsModelValid = false;
            subscription.ErrorMessage = string.Join(";\n", result.Errors);
         }
         
         return JsonNetModelError(subscription);
      }
   }
}

src/TM.UI.MVC/Views/Course/Course.cshtml
@using TM.Shared
@model CourseViewModels.CourseInfoViewModel

@section Title{
    Course - @Model.Title
}

@{
    bool inLearningPlan = User.Identity.IsAuthenticated && Model.LearningState != default(LearningState);
}

<!--Breadcrumbs-->
<ol class="breadcrumb">
    <li><a href="@Url.Content("~/")">Home</a></li>
    <li><a href="@Url.RouteUrl(AppConstants.RouteNames.AllTrainingProviders)">Training Providers</a></li>
    <li><a href="@Url.RouteUrl(AppConstants.RouteNames.TrainingProvider)">@Model.TrainingProvider.Name.ToTitleCaseInvariant()</a></li>
    <li><a href="@Url.RouteUrl(AppConstants.RouteNames.TrainingProviderCategories)">Categories</a></li>
    <li><a href="@Url.RouteUrl(AppConstants.RouteNames.TrainingProviderCategory, Model.Category.CategoryRouteValuesObject)">@Model.Category.Title</a></li>
    <li class="active">...</li>
</ol>


<section class="jumbotron tm-course-info-jumbotron">
    <h2>@Model.Title</h2>
    <p>@MvcHtmlString.Create(Model.ShortDescription)</p>
</section>
<section>

    <!--Authors links-->
    <div class="row">
        <div class="col-xs-12">
            <span>
                by @Html.DisplayCourseAuthors(Model.TrainingProvider.Name, Model.Authors) for <a target="_blank" href="@Model.SiteUrl">
                    <img height="30" src="@Model.TrainingProvider.LogoUrl" alt="@Model.TrainingProvider.Name)" />
                </a>
            </span>
        </div>
    </div>

    <!--Content-->
    <div class="row">
        <div class="col-md-9">

            <!--TOC-->
            <div id="toc-block">

                <!--Header-->
                <h3 class="tm-h3">
                    <span>Table of contents&nbsp;&nbsp;<a id="toc-expand-all" href="#">Expand all</a><a id="toc-collapse-all" href="#">Collapse all</a></span>
                </h3>

                @Html.DisplayFor(m => m.Modules)

            </div>

            <!--Description-->
            <div id="description-block">
                <!--Header-->

                <h3 class="tm-h3">Description</h3>


                <!--Description-->
                <p class="text-justify">@MvcHtmlString.Create(@Model.Description)</p>

                <h3 class="tm-h3">Authored by</h3>

                <!--Authors-->
                <div>
                    @for (var i = 0; i < Model.AuthorsInfo.Count; i++)
                    {
                        <div class="row">
                            <div class=" col-xs-12 tm-container clearfix">

                                @Html.DisplayFor(m => m.AuthorsInfo[i].Avatar)
                                @Html.DisplayFor(m => m.AuthorsInfo[i].Badge)

                                <h3 class="tm-h3">@Model.AuthorsInfo[i].FullName</h3>

                                @Html.DisplayFor(m => m.AuthorsInfo[i].Social)
                                <div class="text-justify">@MvcHtmlString.Create(Model.AuthorsInfo[i].Bio)</div>

                                <a role="button" class="btn btn-primary tm-margin-top" href="@Url.RouteUrl(AppConstants.RouteNames.Author, new { trainingProviderName = Model.TrainingProvider.Name, authorUrlName = Model.AuthorsInfo[i].UrlName })">More by the author</a>
                            </div>
                        </div>

                        <hr />
                    }

                </div>
            </div>

        </div>
        <div class="col-md-3">
            <h3 class="tm-h3">Course info</h3>

            <div class="list-group">
                <a id="toc-link" href="#" class="list-group-item active"><i class="fa fa-list-ul fa-fw fa-lg"></i> Table of contents</a>
                <a id="description-link" href="#" class="list-group-item"><i class="fa fa-info fa-fw fa-lg"></i> Description</a>
            </div>

            @if (User.Identity.IsAuthenticated && !inLearningPlan)
            {
                <div id="tm-form-container">
                    @using (Html.BeginForm("AjaxAdd", "LearningPlan", FormMethod.Post, new { @class = "form-inline", id = "tm-add-form" }))
                    {
                        @Html.AntiForgeryToken()
                        <input type="hidden" name="courseId" value="@Model.Id" />
                        <button type="submit" class="btn btn-success">Add To The Learning Plan</button>

                        <div class="alert alert-success" style="display: none" role="alert">Course added to the learning plan.</div>
                        <div class="alert alert-danger" style="display: none" role="alert">Error occured. Try again later.</div>
                    }
                </div>
            }

            <h3 class="tm-h3">More info</h3>

            <div id="course-more-info" class="list-group">

                <div class="list-group-item clearfix">
                    <div class="pull-left">@Html.DisplayNameFor(m => m.Level)</div>
                    <div class="pull-right">@Html.DisplayFor(m => m.Level)</div>
                </div>
                <div class="list-group-item clearfix">
                    <div class="pull-left">@Html.DisplayNameFor(m => m.Rating)</div>
                    <div class="pull-right">@Html.DisplayCourseRating(Model.Rating)</div>
                </div>
                <div class="list-group-item clearfix">
                    <div class="pull-left">@Html.DisplayNameFor(m => m.Duration)</div>
                    <div class="pull-right">@Html.DisplayFor(m => m.Duration)</div>
                </div>
                <div class="list-group-item clearfix">
                    <div class="pull-left">@Html.DisplayNameFor(m => m.ReleaseDate)</div>
                    <div class="pull-right">@Html.DisplayFor(m => m.ReleaseDate)</div>
                </div>
                <div class="list-group-item clearfix">
                    <div class="pull-left">@Html.DisplayNameFor(m => m.HasClosedCaptions)</div>
                    <div class="pull-right">@Html.DisplayFor(m => m.HasClosedCaptions)</div>
                </div>
            </div>

        </div>
    </div>
</section>

@section scripts
{
    @Scripts.Render("~/bundles/course");
}

src/TM.UI.MVC/Views/Course/Courses.cshtml
@model CourseViewModels.CourseCatalogViewModel

@section Title{
    @{ var title = Model.Navigation.SelectedToken == NavigationViewModel.ALLToken
           ? "Courses"
           : "Courses at " + Model.Navigation.SelectedToken.ToTitleCaseInvariant(); }
    @title
}


<!--Breadcrumbs-->
@if (Model.Navigation.SelectedToken == NavigationViewModel.ALLToken)
{
    <ol class="breadcrumb">
        <li><a href="@Url.Content("~/")">Home</a></li>
        <li class="active">Courses</li>
    </ol>
} else
{
    <ol class="breadcrumb">
        <li><a href="@Url.Content("~/")">Home</a></li>
        <li><a href="@Url.RouteUrl(AppConstants.RouteNames.AllTrainingProviders)">Training Providers</a></li>
        <li><a href="@Url.RouteUrl(AppConstants.RouteNames.TrainingProvider)">@Model.Navigation.SelectedToken.ToTitleCaseInvariant()</a></li>
        <li class="active">Courses</li>
    </ol>
}

<!--Navigation-->
<ul class="nav nav-tabs">
    @foreach (var token in Model.Navigation.TokenCatalog)
    {
        var active = token.Equals(Model.Navigation.SelectedToken, StringComparison.OrdinalIgnoreCase) ? "active" : null;
        var url = token == NavigationViewModel.ALLToken
            ? Url.RouteUrl(AppConstants.RouteNames.AllCourses)
            : Url.RouteUrl(AppConstants.RouteNames.TrainingProviderCourses, new { trainingProviderName = token.ToLowerInvariant() });
        <li role="presentation" class="@active"><a href="@url">@token</a></li>
    }
</ul>


@{Html.RenderPartial("_AjaxCourseListPartial", Model.Metadata);}


@section scripts
{
    @*TODO: Refactor page structure*@
    <script>
        (function ($) {
            $('.tm-data-table').tmDataTableAjax({
                dtSettings: {
                    ajax: {
                        url: '@Url.Action("AjaxSearch")',
                        data: function (data) {
                            data.__RequestVerificationToken = $('[name=__RequestVerificationToken]').val();
                            data.trainingProviderName = '@Model.Navigation.SelectedToken';
                            return data;
                        }
                    }
                }
            });
        })(jQuery);
    </script>
}

src/TM.UI.MVC/Views/Course/Search.cshtml
@model CourseViewModels.CourseSearchViewModel

@section Title{
    Search - @Html.Encode(Model.SearchTerm)
}

<!--Breadcrumbs-->
<ol class="breadcrumb">
    <li><a href="@Url.Content("~/")">Home</a></li>
    <li class="active">Search - @Html.Encode(Model.SearchTerm)</li>
</ol>

@{Html.RenderPartial("_AjaxCourseListPartial", Model.Metadata);}


@section scripts
{
    @*TODO: Refactor page structure*@
    <script>
        (function ($) {
            $('.tm-data-table').tmDataTableAjax({
                dtSettings: {
                    ajax: {
                        url: '@Url.Action("AjaxSearch")',
                        data: function (data) {
                            data.__RequestVerificationToken = $('[name=__RequestVerificationToken]').val();
                            data.searchTerm = '@Model.SearchTerm';
                            return data;
                        }
                    }
                }
            });
        })(jQuery);
    </script>
}

src/TM.UI.MVC/Views/Course/_AjaxCourseListPartial.cshtml
@model CourseCatalogEntryViewModel


@Html.AntiForgeryToken()

<!--Courses Table-->
<table class="table tm-data-table table-bordered table-striped responsive nowrap" data-page-length="10" data-order='[[6, "desc"]]' data-dom="RClrtip">
    <thead>
        <tr>
            <th class="desktop">@Html.DisplayNameFor(m => m.TrainingProvider.Name)</th>
            <th class="min-tablet-l">@Html.DisplayNameFor(m => m.Category.Title)</th>
            <th class="all">@Html.DisplayNameFor(m => m.Course.Title)</th>
            <th class="min-tablet">@Html.DisplayNameFor(m => m.Course.Authors)</th>
            <th class="desktop">@Html.DisplayNameFor(m => m.Course.Level)</th>
            <th class="desktop">@Html.DisplayNameFor(m => m.Course.Duration)</th>
            <th class="min-tablet">@Html.DisplayNameFor(m => m.Course.ReleaseDate)</th>
            <th class="min-tablet-l">@Html.DisplayNameFor(m => m.Course.Rating)</th>
        </tr>
    </thead>
</table>

src/TM.UI.MVC/Views/Course/_CourseListPartial.cshtml
@using TM.Shared
@model CourseViewModels.CourseCatalogViewModel

@Html.AntiForgeryToken()

<!--Courses Table-->
<table class="table tm-data-table table-bordered table-striped" data-actions='{"add":"@Url.Action("AjaxAdd", "LearningPlan")"}'>
    <thead>
        <tr>
            @if (Model.CourseListFor == CourseViewModels.CourseListFor.Author)
            {
                <!--Category-->
                <th class="min-tablet-l">@Html.DisplayNameFor(model => model.Metadata.Category.Title)</th>
            }
            <!--Course-->
            <th id="course-name-column" class="all">@Html.DisplayNameFor(model => model.Metadata.Course.Title)</th>
            <!--Authors-->
            <th class="min-tablet">@Html.DisplayNameFor(model => model.Metadata.Course.Authors)</th>
            <!--Level-->
            <th class ="desktop">@Html.DisplayNameFor(model => model.Metadata.Course.Level)</th>
            <!--Duration-->
            <th class="desktop">@Html.DisplayNameFor(model => model.Metadata.Course.Duration)</th>
            <!--ReleaseDate-->
            <th class="tm-dt-dom-numeric-order text-nowrap min-tablet">@Html.DisplayNameFor(model => model.Metadata.Course.ReleaseDate)</th>
            <!--Rating-->
            <th class="min-tablet-l">@Html.DisplayNameFor(model => model.Metadata.Course.Rating)</th>

            @if (User.Identity.IsAuthenticated)
            {
                <!--Actions-->
                <th id="control-column" class="all tm-dt-not-orderable tm-dt-not-searchable"></th>
                <!--Subscription Token-->
                <th id="token-column" class="never tm-dt-not-orderable">Subscription Token</th>
            }
        </tr>
    </thead>

    <tbody>
        @foreach (var entry in Model.Courses)
        {
            <tr>
                @if (Model.CourseListFor == CourseViewModels.CourseListFor.Author)
                {
                    <!--Category-->
                    <td data-order="@entry.Category.Title">
                        <a href="@Url.RouteUrl(AppConstants.RouteNames.TrainingProviderCategory, entry.CategoryRouteValueObject)">
                            @entry.Category.Title
                        </a>
                    </td>
                }
                <!--Course-->
                <td>
                    @Html.DisplayCourseSubscriptionMarker(entry.Course.LearningState)
                    <a href="@Url.RouteUrl(AppConstants.RouteNames.Course, entry.CourseRouteValueObject)">
                        @entry.Course.Title
                    </a>
                    @if (entry.Course.HasClosedCaptions)
                    {
                        <i class="text-info fa fa-cc"></i>
                    }
                </td>
                <!--Authors-->
                <td data-search="@string.Join(", ", entry.Course.Authors.Select(x => x.FullName))">@Html.DisplayCourseAuthors(entry.TrainingProvider.Name, entry.Course.Authors)</td>
                <!--Level-->
                <td data-order="@(((int) entry.Course.Level).ToString())">@Html.DisplayFor(m => entry.Course.Level)</td>
                <!--Duration-->
                <td data-order="@entry.Course.Duration.Ticks.ToString()">@Html.DisplayFor(m => entry.Course.Duration)</td>
                <!--ReleaseDate-->
                <td data-order="@entry.Course.ReleaseDate.Ticks.ToString()">@Html.DisplayFor(m => entry.Course.ReleaseDate)</td>
                <!--Rating-->
                <td data-order="@entry.Course.Rating.Rating.ToString()">@Html.DisplayCourseRating(entry.Course.Rating)</td>
                @if (User.Identity.IsAuthenticated)
                {
                    <!--Actions-->
                    <td>
                        @{ var disabled = entry.Course.LearningState != default(LearningState) ? "disabled" : null; }

                        <input type="hidden" name="courseId" value="@entry.Course.Id" />
                        <button type="button" data-toggle="tooltip" title="Add to learning plan" class="btn btn-xs btn-success @disabled" data-action="add"><i class="fa fa-plus fa-lg tm-white "></i></button>
                    </td>
                    <!--Subscription Token-->
                    <td>@Html.DisplayCourseSubscriptionToken(entry.Course.LearningState)</td>
                }
            </tr>
        }
    </tbody>
</table>

src/TM.UI.MVC/Views/Course/_TopCourseListPartial.cshtml
@model IEnumerable<CourseViewModels.CourseLinkViewModel>
           
@foreach (var courseLink in Model)
{
    <li class="list-group-item">
        <a href="@Url.RouteUrl(AppConstants.RouteNames.Course, courseLink.CourseRouteValueObject)" class="list-group-item">
            @Html.DisplayFor(m => courseLink.CourseTitle)
        </a>
    </li>
}