src/TM.UI.MVC/Areas/Admin/Controllers/ApplicationUsersController.cs
using System;
using System.Data.Entity;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using TM.UI.MVC.Areas.Admin.ViewModels;
using TM.UI.MVC.ControllableModel;
using TM.UI.MVC.Helpers;

namespace TM.UI.MVC.Areas.Admin.Controllers
{
   using VM = ApplicationUserViewModels;

   [Authorize(Roles = AppConstants.UserRole.Administrator)]
   [SuppressMessage("ReSharper", "LocalizableElement")]
   public class ApplicationUsersController : Controller
   {
      private ApplicationRoleManager _roleManager;
      private ApplicationUserManager _userManager;

      public ApplicationUsersController()
      {

      }

      public ApplicationUsersController(ApplicationRoleManager roleManager, ApplicationUserManager userManager)
      {
         _roleManager = roleManager;
         _userManager = userManager;
      }

      private ApplicationRoleManager RoleManager
      {
         get { return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>(); }
      }

      private ApplicationUserManager UserManager
      {
         get { return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
      }



      public async Task<ActionResult> Index(ControllableViewModelParams modelParams)
      {
         var viewModelQuery = UserManager.Users
            .Select(user => new ApplicationUserViewModels.IndexViewModel
            {
               UserName = user.UserName,
               RegisteredOnUtc = user.RegisteredOnUtc,
               LastLoginOnUtc = user.LastLoginOnUtc,
               LockoutEnabled = user.LockoutEnabled,
               LockoutEndDateUtc = user.LockoutEndDateUtc,
               AccessFailedCount = user.AccessFailedCount,
               IsAdmin = RoleManager.Roles
                  .FirstOrDefault(role => role.Name == AppConstants.UserRole.Administrator)
                  .Users.Any(userRole => userRole.UserId == user.Id)
            });

         var controllableViewModel = await ApplicationUserViewModels.IndexViewModel.ToControlableViewModelAsync(viewModelQuery, modelParams);

         return View(controllableViewModel);
      }


      public async Task<ActionResult> Edit(string userName, ControllableViewModelParams modelParams)
      {
         if (userName == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }

         var viewModel = await UserManager.Users.Where(x => x.UserName == userName)
            .Select(user => new ApplicationUserViewModels.EditViewModel
            {
               UserId = user.Id,
               UserName = user.UserName,
               LockoutEnabled = user.LockoutEnabled,
               LockoutEndDateUtc = user.LockoutEndDateUtc,
               RoleList = RoleManager.Roles
                  .Select(role => new SelectListItem
                  {
                     Value = role.Id,
                     Text = role.Name
                  }).ToList(),
               SelectedRoles = RoleManager.Roles
               .Where(role => role.Users.Any(userRole => userRole.UserId == user.Id))
               .Select(role => role.Id).ToList()
            }).SingleOrDefaultAsync();

         if (viewModel == null)
         {
            return HttpNotFound();
         }

         ViewData.SetControllableViewModelParams(modelParams);

         return View(viewModel);
      }


      [HttpPost]
      [ValidateAntiForgeryToken]
      public async Task<ActionResult> Edit(ApplicationUserViewModels.EditViewModel editModel, ControllableViewModelParams modelParams)
      {
         if (ModelState.IsValid)
         {
            do
            {
               var currentUser = await UserManager.FindByIdAsync(editModel.UserId);

               if (currentUser == null)
               {
                  return HttpNotFound();
               }

               var adminRole = await RoleManager.FindByNameAsync(AppConstants.UserRole.Administrator);
               var currentUserRolesIds = currentUser.Roles.Select(x => x.RoleId).ToList();

               // if user is currently stored having the Administrator role
               var isThisUserAnAdmin = currentUserRolesIds.Contains(adminRole.Id);

               // and the user did not have Administrator role checked
               var isThisUserAdminDeselected = editModel.SelectedRoles.All(roleId => roleId != adminRole.Id);

               // and the current stored count of users with Administrator role == 1
               var isOnlyOneUserAnAdmin = adminRole.Users.Count == 1;

               // then prevent the removal of the Administrator role.
               if (isThisUserAnAdmin && isThisUserAdminDeselected && isOnlyOneUserAnAdmin)
               {
                  ModelState.AddModelError("", "At least one user must retain the 'administrator' role.");
                  break;
               }

               if (currentUser.LockoutEnabled != editModel.LockoutEnabled)
               {
                  currentUser.LockoutEnabled = editModel.LockoutEnabled;

                  var result = await UserManager.UpdateAsync(currentUser);
                  if (!result.Succeeded)
                  {
                     ModelState.AddModelError("", result.Errors.First());
                     break;
                  }
               }

               var allRoles = await RoleManager.Roles.ToListAsync();

               var deletedRolesIds = currentUserRolesIds.Except(editModel.SelectedRoles).ToList();

               if (deletedRolesIds.Any())
               {
                  var rolesToRemove = allRoles
                     .Where(x => deletedRolesIds.Contains(x.Id)).Select(x => x.Name)
                     .ToArray();

                  var result = await UserManager.RemoveFromRolesAsync(currentUser.Id, rolesToRemove);

                  if (!result.Succeeded)
                  {
                     ModelState.AddModelError("", result.Errors.First());
                     break;
                  }
               }


               var newRolesIds = editModel.SelectedRoles.Except(currentUserRolesIds).ToArray();

               if (newRolesIds.Any())
               {
                  var rolesToAdd = allRoles
                     .Where(x => newRolesIds.Contains(x.Id)).Select(x => x.Name)
                     .ToArray();

                  var result = await UserManager.AddToRolesAsync(currentUser.Id, rolesToAdd);

                  if (!result.Succeeded)
                  {
                     ModelState.AddModelError("", result.Errors.First());
                     break;
                  }
               }

               return RedirectToAction("Index", modelParams);
#pragma warning disable 162
            } while (false);
#pragma warning restore 162
         }

         editModel.RoleList = await RoleManager.Roles
            .Select(x => new SelectListItem
            {
               Text = x.Name,
               Value = x.Id
            }).ToListAsync();

         return View(editModel);
      }


      [HttpPost]
      [ValidateAntiForgeryToken]
      public async Task<ActionResult> LockAccount(string userId, ControllableViewModelParams modelParams)
      {
         var currentUser = await UserManager.FindByIdAsync(userId);
         if (currentUser == null)
         {
            return HttpNotFound();
         }

         var userIsAnAdministrator = await UserManager.IsInRoleAsync(currentUser.Id, AppConstants.UserRole.Administrator);

         if (userIsAnAdministrator)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Cannot lock user in an administrator role.");
         }

         await UserManager.ResetAccessFailedCountAsync(currentUser.Id);
         await UserManager.SetLockoutEndDateAsync(currentUser.Id, DateTimeOffset.UtcNow.AddYears(1));

         return RedirectToAction("Index", modelParams);
      }


      [HttpPost]
      [ValidateAntiForgeryToken]
      public async Task<ActionResult> UnLockAccount(string userId, ControllableViewModelParams modelParams)
      {
         var currentUser = await UserManager.FindByIdAsync(userId);
         if (currentUser == null)
         {
            return HttpNotFound();
         }

         await UserManager.ResetAccessFailedCountAsync(currentUser.Id);
         await UserManager.SetLockoutEndDateAsync(currentUser.Id, DateTimeOffset.UtcNow);

         return RedirectToAction("Index", modelParams);
      }

      protected override void Dispose(bool disposing)
      {
         if (disposing)
         {
            if (_userManager != null)
            {
               _userManager.Dispose();
               _userManager = null;
            }
            if (_roleManager != null)
            {
               _roleManager.Dispose();
               _roleManager = null;
            }
         }
         base.Dispose(disposing);
      }
   }
}

src/TM.UI.MVC/Areas/Admin/Views/ApplicationUsers/Edit.cshtml
@model ApplicationUserViewModels.EditViewModel

@section Title{
    Edit User
}

<h2>Edit User</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsLocked)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsLocked)
            @using (Html.BeginForm(Model.IsLocked ? "UnLockAccount" : "LockAccount", "ApplicationUsers", FormMethod.Post, new { style="display: inline" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.UserId)
                
                @ViewData.GetControllableViewModelParams().ToHiddenFields()
                
                <input type="submit" class="btn btn-danger btn-xs" value=" @Html.IfElse(Model.IsLocked, "Unlock user", "Lock User") ">
            }
        </dd>
        <dd>
            @Html.If(Model.IsLocked, () => Html.DisplayFor(model => model.LockoutEndDateUtc))
        </dd>

    </dl>
</div>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @ViewData.GetControllableViewModelParams().ToHiddenFields()
        @Html.HiddenFor(model => model.UserId)
        @Html.HiddenFor(model => model.LockoutEndDateUtc)

        <div class="form-group">
            @Html.LabelFor(model => model.LockoutEnabled, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.LockoutEnabled, Model.LockoutSelectList, new { @calss = "form-control" })

                @Html.ValidationMessageFor(model => model.LockoutEnabled, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedRoles, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxListFor(model => model.SelectedRoles, Model.RoleList)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Back to List", "Index", ViewData.GetControllableViewModelParams(), new { @class = "btn btn-default btn-sm" })
                <input type="submit" value="Save" class="btn btn-success btn-sm" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/TM.UI.MVC/Areas/Admin/Views/ApplicationUsers/Index.cshtml
@using PagedList.Mvc
@model ApplicationUserViewModels.IndexControllableViewModel

@section Title{
    User List
}

<h2>User List</h2>

@Html.DisplayForModel("IControllableView")

<table class="table table-striped table-condensed table-responsive">
    <tr>
        <th>
            @Html.ActionLink(Html.DisplayNameFor(model => model.Metadata.UserName).ToString(), "Index", Model.Params.ToRouteValueDictionary(Model.SortState.NicknameSortState))
        </th>
        <th>
            @Html.ActionLink(Html.DisplayNameFor(model => model.Metadata.RegisteredOnUtc).ToString(), "Index", Model.Params.ToRouteValueDictionary(Model.SortState.RegistrationDateSortState))
        </th>
        <th>
            @Html.ActionLink(Html.DisplayNameFor(model => model.Metadata.LastLoginOnUtc).ToString(), "Index", Model.Params.ToRouteValueDictionary(Model.SortState.LastLoginDateSortState))
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Metadata.LockoutEnabled)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Metadata.LockoutEndDateUtc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Metadata.AccessFailedCount)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model.PagedList)
    {
        var mark = item.IsAdmin
            ? "text-muted"
            : item.IsLocked
                ? "text-danger"
                : null;

        <tr class="@mark">
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegisteredOnUtc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastLoginOnUtc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LockoutEnabled)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LockoutEndDateUtc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AccessFailedCount)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", Model.Params.ToRouteValueDictionary().Include(new { item.UserName }))
            </td>
        </tr>
    }

</table>

 Page @Model.PagedList.PageNumber of @Model.PagedList.PageCount


@Html.PagedListPager(Model.PagedList, page => Url.Action("Index", Model.Params.ToRouteValueObject(page)))

@section scripts
{
    @{ Html.RenderPartial("_IControllableViewScript");}
}