src/TM.UI.MVC/Areas/Admin/Controllers/UpdateEventsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using TM.Data.Update;
using TM.Shared;
using TM.UI.MVC.Areas.Admin.ViewModels;
using TM.UI.MVC.ControllableModel;
using TM.UI.MVC.Helpers;

namespace TM.UI.MVC.Areas.Admin.Controllers
{
   using VM = UpdateEventViewModels;

   [Authorize(Roles = AppConstants.UserRole.Administrator)]
   public class UpdateEventsController : Controller
   {
      private UpdateDbContext db = new UpdateDbContext();



      public async Task<ActionResult> Index(ControllableViewModelParams modelParams)
      {
         var updateEventsQuery = db.UpdateEvents.Select(x => new UpdateEventViewModels.IndexViewModel
         {
            Id = x.Id,
            TrainingProviderName = x.TrainingProvider.Name,
            Description = x.Description,
            StartedOn = x.StartedOn,
            EndedOn = x.EndedOn,
            UpdateResult = x.UpdateResult
         });

         var controllableViewModel = await UpdateEventViewModels.IndexViewModel.ToControlableViewModelAsync(updateEventsQuery, modelParams);

         return View(controllableViewModel);
      }


      public async Task<ActionResult> Details(int? id, ControllableViewModelParams modelParams)
      {
         if (id == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }

         var updateEvent = await db.UpdateEvents.Where(x => x.Id == id).Select(x => new UpdateEventViewModels.DetailsViewModel
         {
            Id = x.Id,
            TrainingProviderName = x.TrainingProvider.Name,
            Description = x.Description,
            StartedOn = x.StartedOn,
            EndedOn = x.EndedOn,
            ErrorData = x.ErrorData,
            UpdateResult = x.UpdateResult,
            Added = new UpdateEventViewModels.StatisticViewModel
            {
               Categories = x.Added.Categories,
               Courses = x.Added.Courses,
               Authors = x.Added.Authors,

               HasCategoriesUpdateLog = x.CategoriesUpdates.Any(u => u.OperationType == OperationType.Add),
               HasCoursesUpdateLog = x.CoursesUpdates.Any(u => u.OperationType == OperationType.Add),
               HasAuthorsUpdateLog = x.AuthorsUpdates.Any(u => u.OperationType == OperationType.Add)
            },
            Deleted = new UpdateEventViewModels.StatisticViewModel
            {
               Categories = x.Deleted.Categories,
               Courses = x.Deleted.Courses,
               Authors = x.Deleted.Authors,

               HasCategoriesUpdateLog = x.CategoriesUpdates.Any(u => u.OperationType == OperationType.Delete),
               HasCoursesUpdateLog = x.CoursesUpdates.Any(u => u.OperationType == OperationType.Delete),
               HasAuthorsUpdateLog = x.AuthorsUpdates.Any(u => u.OperationType == OperationType.Delete)
            },
            Modified = new UpdateEventViewModels.StatisticViewModel
            {
               Categories = x.Modified.Categories,
               Courses = x.Modified.Courses,
               Authors = x.Modified.Authors,

               HasCategoriesUpdateLog = x.CategoriesUpdates.Any(u => u.OperationType == OperationType.Modify),
               HasCoursesUpdateLog = x.CoursesUpdates.Any(u => u.OperationType == OperationType.Modify && u.CourseBackup != null),
               HasAuthorsUpdateLog = x.AuthorsUpdates.Any(u => u.OperationType == OperationType.Modify)
            }
         }).SingleOrDefaultAsync();

         if (updateEvent == null)
         {
            return HttpNotFound();
         }

         ViewData.SetControllableViewModelParams(modelParams);

         return View(updateEvent);
      }



      public async Task<ActionResult> CategoriesUpdateDetails(int? id, OperationType? operation)
      {
         if (operation == null || operation == OperationType.None)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }

         var categoriesQuery = operation == OperationType.Modify
                    ? db.CategoriesUpdates
                       .Where(x => x.UpdateEventId == id && x.OperationType == operation && x.CategoryBackup.UpdateEventId == x.UpdateEventId)
                    : db.CategoriesUpdates
                       .Where(x => x.UpdateEventId == id && x.OperationType == operation);

         var viewModel = await db.UpdateEvents
            .Where(x => x.Id == id)
            .Select(x => new UpdateEventViewModels.CategoryUpdateDetailsViewModel
            {
               UpdateEventId = x.Id,
               OperationType = operation.Value,
               TrainingProviderName = x.TrainingProvider.Name,
               Categories = categoriesQuery.Select(c => new UpdateEventViewModels.CategoryUpdateListViewModel
               {
                  CategoryId = c.CategoryId,
                  Title = c.Category.Title,
                  CategoryUrlName = c.Category.UrlName
               }).ToList()
            }).SingleOrDefaultAsync();

         if (viewModel == null)
         {
            return HttpNotFound();
         }

         return View(viewModel);
      }


      public async Task<ActionResult> CategoryChangesDetails(int? updateEventId, int? categoryId)
      {
         if (updateEventId == null || categoryId == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }

         var viewModel = await db.CategoriesBackups
            .Where(x => x.UpdateEventId == updateEventId && x.CategoryId == categoryId)
            .Select(x => new UpdateEventViewModels.CategoryChangesDetailsViewModel
            {
               TrainingProviderName = x.CategoryUpdate.UpdateEvent.TrainingProvider.Name,

               PreviousContent = new UpdateEventViewModels.CategoryChangesViewModel
               {
                  Title = x.Title,
                  LogoUrl = x.LogoUrl,
                  LogoFileName = x.LogoFileName
               },
               CurrentContent = new UpdateEventViewModels.CategoryChangesViewModel
               {
                  Title = x.CategoryUpdate.Category.Title,
                  LogoUrl = x.CategoryUpdate.Category.LogoUrl,
                  LogoFileName = x.CategoryUpdate.Category.LogoFileName
               }
            }).SingleOrDefaultAsync();

         return View(viewModel);
      }




      public async Task<ActionResult> CoursesUpdateDetails(int? id, OperationType? operation)
      {
         if (operation == null || operation == OperationType.None)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }

         var coursesQuery = operation == OperationType.Modify
            ? db.CoursesUpdates
               .Where(x => x.UpdateEventId == id && x.OperationType == operation && x.CourseBackup.UpdateEventId == x.UpdateEventId)
            : db.CoursesUpdates
               .Where(x => x.UpdateEventId == id && x.OperationType == operation);

         var viewModel = await db.UpdateEvents
            .Where(x => x.Id == id)
            .Select(x => new UpdateEventViewModels.CourseUpdateDetailsViewModel
            {
               UpdateEventId = x.Id,
               OperationType = operation.Value,
               TrainingProviderName = x.TrainingProvider.Name,
               Courses = coursesQuery.Select(c => new UpdateEventViewModels.CourseUpdateListViewModel
               {
                  CourseId = c.CourseId,
                  CategoryTitle = c.Course.Category.Title,
                  CategoryUrlName = c.Course.Category.UrlName,
                  CourseTitle = c.Course.Title,
                  CourseUrlName = c.Course.UrlName,
                  CourseReleaseDate = c.Course.ReleaseDate
               }).OrderByDescending(c => c.CourseReleaseDate).ToList()
            }).SingleOrDefaultAsync();

         if (viewModel == null)
         {
            return HttpNotFound();
         }

         return View(viewModel);
      }

      public async Task<ActionResult> CourseChangesDetails(int? updateEventId, int? courseId)
      {
         if (updateEventId == null || courseId == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }

         var viewModel = await db.CoursesBackups
            .Where(x => x.UpdateEventId == updateEventId && x.CourseId == courseId)
            .Select(x => new UpdateEventViewModels.CourseChangesDetailsViewModel
            {
               HasAuthorsChanges = x.CourseAuthorBackups.Any(),
               TrainingProviderName = x.CourseUpdate.Course.TrainingProvider.Name,

               PreviousContent = new UpdateEventViewModels.CourseChangesViewModel
               {
                  CategoryTitle = x.Category.Title,
                  CategoryUrlName = x.Category.UrlName,
                  Title = x.Title,
                  SiteUrl = x.SiteUrl,
                  Description = x.Description,
                  ReleaseDate = x.ReleaseDate,
                  CourseLevel = (CourseLevel?) x.CourseLevel,
                  HasClosedCaptions = x.HasClosedCaptions,
                  Duration = x.Duration,
                  AuthorsChanges = x.CourseAuthorBackups
                     .Select(a => new UpdateEventViewModels.CourseAuthorsChangesViewModel
                     {
                        FullName = a.TrainingProviderAuthor.FullName,
                        AuthorUrlName = a.TrainingProviderAuthor.UrlName,
                        IsAuthorCoAuthor = a.IsAuthorCoAuthor,
                        OperationType = a.OperationType
                     }).ToList()
               },
               CurrentContent = new UpdateEventViewModels.CourseChangesViewModel
               {
                  CategoryTitle = x.CourseUpdate.Course.Category.Title,
                  CategoryUrlName = x.CourseUpdate.Course.Category.UrlName,
                  Title = x.CourseUpdate.Course.Title,

src/TM.UI.MVC/Areas/Admin/Views/UpdateEvents/AuthorChangesDetails.cshtml
@model UpdateEventViewModels.AuthorChangesDetailsViewModel

@section Title{
    Author Change Details
}

<h2>Author Change Details</h2>
<hr />
<h4>Author: <strong>@Model.CurrentContent.FullName</strong></h4>

<table class="table table-condensed table-responsive">
    <tr>
        <th>Property Name</th>
        <th>@Html.DisplayNameFor(model => model.CurrentContent)</th>
        <th>@Html.DisplayNameFor(model => model.PreviousContent)</th>
    </tr>

    @if (Model.PreviousContent.FullName != null)
    {
        <tr>
            <td>@Html.DisplayNameFor(m => m.CurrentContent.FullName)</td>
            <td>@Html.DisplayFor(m => m.CurrentContent.FullName)</td>
            <td>@Html.DisplayFor(m => m.PreviousContent.FullName)</td>
        </tr>

    }


    @if (Model.PreviousContent.SiteUrl != null)
    {
        <tr>
            <td>@Html.DisplayNameFor(m => m.CurrentContent.SiteUrl)</td>
            <td>@Html.DisplayFor(m => m.CurrentContent.SiteUrl)</td>
            <td>@Html.DisplayFor(m => m.PreviousContent.SiteUrl)</td>
        </tr>
    }

</table>

src/TM.UI.MVC/Areas/Admin/Views/UpdateEvents/AuthorsUpdateDetails.cshtml
@using TM.Data.Update
@model UpdateEventViewModels.AuthorUpdateDetailsViewModel

@section Title{
    Authors Update Details
}

<h2>Authors Update Details</h2>

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.UpdateEventId)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.UpdateEventId)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.TrainingProviderName)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.TrainingProviderName)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.OperationType)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.OperationType)
    </dd>
</dl>


<table class="table table-condensed table-responsive">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AuthorsMetadata.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AuthorsMetadata.SiteUrl)
        </th>
        @if (Model.OperationType == OperationType.Modify)
        {
            <th></th>
        }
    </tr>

    @foreach (var author in Model.Authors)
    {
        <tr>
            <td>
                <a target="_blank" href="@Url.RouteUrl(AppConstants.RouteNames.Author, new { Model.TrainingProviderName, author.AuthorUrlName })">
                    @Html.DisplayFor(m => author.FullName)
                </a>
            </td>
            <td>
                <a target="_blank" href="@Html.DisplayFor(m => author.SiteUrl)">
                    @Html.DisplayFor(m => author.SiteUrl)
                </a>
                
            </td>
            @if (Model.OperationType == OperationType.Modify)
            {
                <td>
                    @Html.ActionLink("Details", "AuthorChangesDetails", "UpdateEvents", new { Model.UpdateEventId, author.AuthorId }, null)
                </td>
            }
        </tr>
    }

</table>

src/TM.UI.MVC/Areas/Admin/Views/UpdateEvents/CategoriesUpdateDetails.cshtml
@using TM.Data.Update
@model UpdateEventViewModels.CategoryUpdateDetailsViewModel

@section Title{
    Categories Update Details
}

<h2>Categories Update Details</h2>

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.UpdateEventId)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.UpdateEventId)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.TrainingProviderName)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.TrainingProviderName)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.OperationType)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.OperationType)
    </dd>
</dl>


<table class="table table-striped table-condensed table-responsive">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CategoriesMetadata.Title)
        </th>

        @if (Model.OperationType == OperationType.Modify)
        {
            <th></th>
        }
    </tr>

    @foreach (var category in Model.Categories)
    {
        <tr>
            <td>
                <a target="_blank" href="@Url.RouteUrl(AppConstants.RouteNames.TrainingProviderCategory, new { Model.TrainingProviderName, category.CategoryUrlName })">
                    @Html.DisplayFor(m => category.Title)
                </a>
            </td>

            @if (Model.OperationType == OperationType.Modify)
            {
                <td>
                    @Html.ActionLink("Details", "CategoryChangesDetails", "UpdateEvents", new { Model.UpdateEventId, category.CategoryId }, null)
                </td>
            }
        </tr>
    }

</table>

src/TM.UI.MVC/Areas/Admin/Views/UpdateEvents/CategoryChangesDetails.cshtml
@model UpdateEventViewModels.CategoryChangesDetailsViewModel

@section Title{
    Category Change Details
}

<h2>Category Change Details</h2>
<hr />
<h4>Category: <strong>@Model.CurrentContent.Title</strong></h4>

<table class="table table-condensed table-responsive">
    <tr>
        <th>Property Name</th>
        <th>@Html.DisplayNameFor(model => model.CurrentContent)</th>
        <th>@Html.DisplayNameFor(model => model.PreviousContent)</th>
    </tr>

    @if (Model.PreviousContent.Title != null)
    {
        <tr>
            <td>@Html.DisplayNameFor(m => m.CurrentContent.Title)</td>
            <td>@Html.DisplayFor(m => m.CurrentContent.Title)</td>
            <td>@Html.DisplayFor(m => m.PreviousContent.Title)</td>
        </tr>

    }


    @if (Model.PreviousContent.LogoUrl != null)
    {
        <tr>
            <td>@Html.DisplayNameFor(m => m.CurrentContent.LogoUrl)</td>
            <td>@Html.DisplayFor(m => m.CurrentContent.LogoUrl)</td>
            <td>@Html.DisplayFor(m => m.PreviousContent.LogoUrl)</td>
        </tr>
    }

    @if (Model.PreviousContent.LogoFileName != null)
    {
        <tr>
            <td>@Html.DisplayNameFor(m => m.CurrentContent.LogoFileName)</td>
            <td>@Html.DisplayFor(m => m.CurrentContent.LogoFileName)</td>
            <td>@Html.DisplayFor(m => m.PreviousContent.LogoFileName)</td>
        </tr>
    }

</table>

src/TM.UI.MVC/Areas/Admin/Views/UpdateEvents/CourseChangesDetails.cshtml
@using TM.Data.Update
@model UpdateEventViewModels.CourseChangesDetailsViewModel
@section Title{
    Course Change Details
}

<h2>Course Change Details</h2>
<hr />
<h4>Course: <strong>@Model.CurrentContent.Title</strong></h4>

<table class="table table-condensed table-responsive">
    <tr>
        <th>Property Name</th>
        <th>@Html.DisplayNameFor(model => model.CurrentContent)</th>
        <th>@Html.DisplayNameFor(model => model.PreviousContent)</th>
    </tr>

    @if (Model.PreviousContent.CategoryTitle != null)
    {
        <tr>
            <td>@Html.DisplayNameFor(m => m.CurrentContent.CategoryTitle)</td>
            <td>
                <a target="_blank" href="@Url.RouteUrl(AppConstants.RouteNames.TrainingProviderCategory, new { Model.TrainingProviderName, Model.CurrentContent.CategoryUrlName })">
                    @Html.DisplayFor(m => m.CurrentContent.CategoryTitle)
                </a>
            </td>
            <td>
                <a target="_blank" href="@Url.RouteUrl(AppConstants.RouteNames.TrainingProviderCategory, new { Model.TrainingProviderName, Model.PreviousContent.CategoryUrlName })">
                    @Html.DisplayFor(m => m.PreviousContent.CategoryTitle)
                </a>
            </td>
        </tr>

    }


    @if (Model.PreviousContent.Title != null)
    {
        <tr>
            <td>@Html.DisplayNameFor(m => m.CurrentContent.Title)</td>
            <td>@Html.DisplayFor(m => m.CurrentContent.Title)</td>
            <td>@Html.DisplayFor(m => m.PreviousContent.Title)</td>
        </tr>
    }

    @if (Model.PreviousContent.SiteUrl != null)
    {
        <tr>
            <td>@Html.DisplayNameFor(m => m.CurrentContent.SiteUrl)</td>
            <td>@Html.DisplayFor(m => m.CurrentContent.SiteUrl)</td>
            <td>@Html.DisplayFor(m => m.PreviousContent.SiteUrl)</td>
        </tr>
    }

    @if (Model.PreviousContent.Description != null)
    {
        <tr>
            <td>@Html.DisplayNameFor(m => m.CurrentContent.Description)</td>
            <td>@Html.DisplayFor(m => m.CurrentContent.Description)</td>
            <td>@Html.DisplayFor(m => m.PreviousContent.Description)</td>
        </tr>
    }

    @if (Model.PreviousContent.HasClosedCaptions != null)
    {
        <tr>
            <td>@Html.DisplayNameFor(m => m.CurrentContent.HasClosedCaptions)</td>
            <td>@Html.DisplayFor(m => m.CurrentContent.HasClosedCaptions)</td>
            <td>@Html.DisplayFor(m => m.PreviousContent.HasClosedCaptions)</td>
        </tr>
    }

    @if (Model.PreviousContent.CourseLevel != null)
    {
        <tr>
            <td>@Html.DisplayNameFor(m => m.CurrentContent.CourseLevel)</td>
            <td>@Html.DisplayFor(m => m.CurrentContent.CourseLevel)</td>
            <td>@Html.DisplayFor(m => m.PreviousContent.CourseLevel)</td>
        </tr>
    }


    @if (Model.PreviousContent.Duration != null)
    {
        <tr>
            <td>@Html.DisplayNameFor(m => m.CurrentContent.Duration)</td>
            <td>@Html.DisplayFor(m => m.CurrentContent.Duration)</td>
            <td>@Html.DisplayFor(m => m.PreviousContent.Duration)</td>
        </tr>
    }

    @if (Model.PreviousContent.ReleaseDate != null)
    {
        <tr>
            <td>@Html.DisplayNameFor(m => m.CurrentContent.ReleaseDate)</td>
            <td>@Html.DisplayFor(m => m.CurrentContent.ReleaseDate)</td>
            <td>@Html.DisplayFor(m => m.PreviousContent.ReleaseDate)</td>
        </tr>
    }

</table>


@if (Model.HasAuthorsChanges)
{
    if (Model.PreviousContent.AuthorsChanges.Any(x => x.OperationType == OperationType.Add))
    {
        <h4>Added Authors</h4>

        <div class="row tm-line-bound">
            @foreach (var author in Model.PreviousContent.AuthorsChanges.Where(x => x.OperationType == OperationType.Add))
            {
                <div class="col-lg-2 col-md-2 col-sm-3 col-xs-12">
                    <div class="well well-sm">
                        <a target="_blank" href="@Url.RouteUrl(AppConstants.RouteNames.Author, new { Model.TrainingProviderName, author.AuthorUrlName })">
                            @Html.DisplayFor(m => author.FullName)
                        </a>
                    </div>
                </div>
            }
        </div>
    }
    if (Model.PreviousContent.AuthorsChanges.Any(x => x.OperationType == OperationType.Delete))
    {
        <h4>Deleted Authors</h4>

        <div class="row tm-line-bound">
            @foreach (var author in Model.PreviousContent.AuthorsChanges.Where(x => x.OperationType == OperationType.Delete))
            {
                <div class="col-lg-2 col-md-2 col-sm-3 col-xs-12">
                    <div class="well well-sm">
                        <a target="_blank" href="@Url.RouteUrl(AppConstants.RouteNames.Author, new { Model.TrainingProviderName, author.AuthorUrlName })">
                            @Html.DisplayFor(m => author.FullName)
                        </a>
                    </div>
                </div>
            }
        </div>
    }

    if (Model.PreviousContent.AuthorsChanges.Any(x => x.OperationType == OperationType.Modify))
    {
        <h4>Modified Authors</h4>

        <div class="row tm-line-bound">
            @foreach (var author in Model.PreviousContent.AuthorsChanges.Where(x => x.OperationType == OperationType.Modify))
            {
                var currentAuthor = Model.CurrentContent.AuthorsChanges.Single(x => x.FullName == author.FullName);
                <div class="col-lg-2 col-md-2 col-sm-3 col-xs-12">
                    <div class="well well-sm">
                        <a target="_blank" href="@Url.RouteUrl(AppConstants.RouteNames.Author, new { Model.TrainingProviderName, author.AuthorUrlName })">
                            @Html.DisplayFor(m => author.FullName)
                        </a>
                        now @Html.DisplayFor(m => currentAuthor.IsAuthorCoAuthor)
                    </div>
                </div>
            }
        </div>
    }
}

src/TM.UI.MVC/Areas/Admin/Views/UpdateEvents/CoursesUpdateDetails.cshtml
@using TM.Data.Update
@model UpdateEventViewModels.CourseUpdateDetailsViewModel

@section Title{
    Courses Update Details
}

<h2>Courses Update Details</h2>

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.UpdateEventId)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.UpdateEventId)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.TrainingProviderName)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.TrainingProviderName)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.OperationType)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.OperationType)
    </dd>
</dl>

<table class="table table-condensed table-responsive">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CoursesMetadata.CategoryTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CoursesMetadata.CourseTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CoursesMetadata.CourseReleaseDate)
        </th>
        @if (Model.OperationType == OperationType.Modify)
        {
            <th></th>
        }
    </tr>

    @foreach (var item in Model.Courses)
    {
        <tr>
            <td>
                <a target="_blank" href="@Url.RouteUrl(AppConstants.RouteNames.TrainingProviderCategory, new { Model.TrainingProviderName, item.CategoryUrlName })">
                    @Html.DisplayFor(m => item.CategoryTitle)
                </a> 
             </td>
            <td>
                <a target="_blank" href="@Url.RouteUrl(AppConstants.RouteNames.Course, new { Model.TrainingProviderName, item.CategoryUrlName, item.CourseUrlName })">
                    @Html.DisplayFor(m => item.CourseTitle)
                </a> 
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseReleaseDate)
            </td>
            @if (Model.OperationType == OperationType.Modify)
            {
                <td>
                    @Html.ActionLink("Details", "CourseChangesDetails", "UpdateEvents", new {Model.UpdateEventId, item.CourseId }, null)
                </td>
            }
        </tr>
    }

</table>

src/TM.UI.MVC/Areas/Admin/Views/UpdateEvents/_StatisticViewModel.cshtml
@model UpdateEventViewModels.StatisticViewModel

@if (Model.HasCategoriesUpdateLog)
{
    <a target="_blank" href="@Url.Action("CategoriesUpdateDetails", "UpdateEvents", new {id = ViewData["id"], operation = ViewData["operation"]})">
        @Html.DisplayNameFor(model => model.Categories): @Html.DisplayFor(m => m.Categories)
    </a>
} else
{
    @: @Html.DisplayNameFor(model => model.Categories): @Html.DisplayFor(m => m.Categories)
}
<br />

@if (Model.HasCoursesUpdateLog)
{
    <a target="_blank" href="@Url.Action("CoursesUpdateDetails", "UpdateEvents", new { id = ViewData["id"], operation = ViewData["operation"] })">
        @Html.DisplayNameFor(model => model.Courses): @Html.DisplayFor(m => m.Courses)
    </a>
} else
{
    @: @Html.DisplayNameFor(model => model.Courses): @Html.DisplayFor(m => m.Courses)
}
<br />

@if (Model.HasAuthorsUpdateLog)
{
    <a target="_blank" href="@Url.Action("AuthorsUpdateDetails", "UpdateEvents", new { id = ViewData["id"], operation = ViewData["operation"] })">
        @Html.DisplayNameFor(model => model.Authors): @Html.DisplayFor(m => m.Authors)
    </a>
} else
{
    @: @Html.DisplayNameFor(model => model.Authors): @Html.DisplayFor(m => m.Authors)
}
<br />